config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    root to: "homes#top"
    get 'home/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :books, only: [:new, :index, :show, :create, :destroy, :edit, :update] do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :book_comments, dependent: :destroy

         has_many :user_rooms, dependent: :destroy
         has_many :chats, dependent: :destroy
         has_many :rooms, through: :user_rooms

         # フォローをした、されたの関係
         has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

         # 一覧画面で使う
         has_many :following_users, through: :followers, source: :followed
         has_many :follower_users, through: :followeds, source: :follower
         has_one_attached :profile_image


          validates :introduction,
    length: {  maximum: 50 }
            validates :name,
    length: { minimum: 2, maximum: 20 }
    validates :name, uniqueness: true

     def get_profile_image(width, height)
       unless profile_image.attached?
         file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
         profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
       end
       profile_image.variant(resize_to_limit: [width, height]).processed
     end

     #　フォローしたときの処理
     def follow(user_id)
        followers.create(followed_id: user_id)
     end

#　フォローを外すときの処理
     def unfollow(user_id)
        followers.find_by(followed_id: user_id).destroy
     end

#フォローしていればtrueを返す
     def following?(user)
        following_users.include?(user)
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
     @book = Book.new(book_params)
  end
  def show
     @book = Book.new
     @user = User.find(params[:id])
    @books = @user.books
    @following_users = @user.following_users
    @follower_users = @user.follower_users
  end


  def index
    @book = Book.new
    @users = User.all
    @user= current_user
  end

  def edit
      is_matching_login_user
    @user = User.find(params[:id])

  end

   def update
       is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:alert] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
       flash.now[:alert] = "error"
       render :edit
    end
   end

   # フォロー一覧
    def follows
      user = User.find(params[:id])
      @users = user.following_users
    end

    # フォロワー一覧
    def followers
      user = User.find(params[:id])
      @user = user.follower_users
    end



  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_list.html.erb
<main>
<div class="container px-5 pz-sm-0">
  <div class="row">
    
     <h2>User info</h2>
  <%= image_tag @user.get_profile_image(100,100) %>
  <table class="table">
  <tbody>

  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody>
</table>




  <% if @user == current_user %>
  <button class="fa-solid fa-user-gear" style="color: #707070;"><%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block" %></button>



  <% end %>
</div>

<div>
  <h2>New book</h2>
  <%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>
</div>

</div>
</div>
</main>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>




<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
   <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->

<div class="main container ">
  <div class="row">

<div class="col-md-3">

     <div class=userinfo>
       <h2>User info</h2>
 <% if @user == current_user %>
  <%= image_tag current_user.get_profile_image(100,100) %>
  <table class="table">
  <tbody>

  <tr>
	  <th>name</th>
	  <th><%= current_user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= current_user.introduction %></th>
  </tr>
</tbody>
</table>




  <div class="row">
     <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
    <% end %>
    </div>

    <% else %>

    <%= image_tag @user.get_profile_image(100,100) %>
  <table class="table">
  <tbody>

  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody>
</table>




  <div class="row">
     <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
   <i class="fas fa-user-cog"></i>
    <% end %>
    </div>


<!--if @book.user == current_user %>の終了-->
<% end %>

<!--userinfoの終了タグ-->
     </div>


<div　class=newbook>
  <h2>New book</h2>
  <%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>
</div>

<!--colの終了-->


<!--sidebar-->







<div class="col-md-8 offset-md-1">
  <!--ここから置き換え-->

  <h2>Books</h2>

  <table class="table table-hover table-inverse">
    <thred>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thred>

    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= link_to "/users/#{book.user.id}" do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %></td>
        <td>
         <p><%= link_to book.title, book_path(book.id) %></p>
          </td>
        <td>
        <p><%= book.body %></p>
          </td>
          <td>
            <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete do %>
         <i class="fa-solid fa-heart" style="color: #ec0941;"></i><%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post do %>
        <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
      <% end %>
    </p>
  <% end %>
          </td>
          <td>
             <p><%=  "コメント数：#{book.book_comments.count} " %></p>
          </td>

      </tr>
       <% end %>
    </tbody>
  </table>


<!--ここまで置き換えcol8offset-->
</div>

<!--row-->
</div>
<!--main container-->
</div>



<!-- ユーザーの投稿一覧 -->