config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    root to: "homes#top"
    get 'home/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :books, only: [:new, :index, :show, :create, :destroy, :edit, :update] do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }

  validates :title, presence: true
  validates :body, presence: true

  validates :body,
    length: { maximum: 200 }
    
    def favorited_by?(user)
    favorites.exists?(user_id: user.id)
    end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @new_book = Book.new
  end

   # 投稿データの保存
  def create
    @user= current_user

    @new_book = Book.new(book_params)
    @books = Book.all
    @book = Book.new(book_params)

    @book.user_id = current_user.id
    if @book.save
        redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render :index
    end
  end

   def index
    @book = Book.new
    @books = Book.all
    @user= current_user
   end



  def show
      @new_book = Book.new
    @book =  Book.find(params[:id])
     @user = @book.user
     @book_comment = BookComment.new

  end

  def edit

    @book = Book.find(params[:id])

    unless @book.user.id == current_user.id
      redirect_to books_path
    end
    @user= current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:alert] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
       render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

    # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true, url: books_path do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
  <label for="inputTitle">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"title"%><br>
  <label for="inputBody">Opinion</label>
  <%= f.text_field :body, autofocus: true, id:"inputBody", placeholder:"body"%><br>
<%= f.submit "Update Book", class:"btn btn-success" %>

<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image(50,50) %>
                <% end %>
              </td>
              <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
              <td><% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
                      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
                      <%= book.favorites.count %>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
                     <i class="fas fa-heart" aria-hidden="true"></i>
                     <%= book.favorites.count %>
                    <% end %>
                  <% end %></td>
              <td><%= render "book_comments/counter", book: book %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>フォーム</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>

  <h4>ショップ名</h4>
  <%= f.text_field :title %>
  <h4>説明</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><% if @book.favorited_by?(current_user) %>
                    <%= link_to book_favorites_path(@book), method: :delete, remote: true do %>
                      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
                      <%= @book.favorites.count %>
                    <% end %>
              <% else %>
                    <%= link_to book_favorites_path(@book), method: :post, remote: true do %>
                     <i class="fas fa-heart" aria-hidden="true"></i>
                     <%= @book.favorites.count %>
                    <% end %>
              <% end %>
            </td>
            <td class="book-comments-counter">
            <%= render "book_comments/counter", book: @book %>
            </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <div class="book-comments-index">
        <%= render "book_comments/index", book: @book %>
      </div>

      <%= render "book_comments/form", book: @book, book_comment: @book_comment %>

    </div>
  </div>
</div>