config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    root to: "homes#top"
    get 'home/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :books, only: [:new, :index, :show, :create, :destroy, :edit, :update] do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
    end
    resources :chats, only: [:show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }

  validates :title, presence: true
  validates :body, presence: true

  validates :body,
    length: { maximum: 200 }
    
    def favorited_by?(user)
    favorites.exists?(user_id: user.id)
    end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

   validates :user_id, uniqueness: {scope: :book_id}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :user_rooms, dependent: :destroy
    has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :book_comments, dependent: :destroy

         has_many :user_rooms, dependent: :destroy
         has_many :chats, dependent: :destroy
         has_many :rooms, through: :user_rooms

         # フォローをした、されたの関係
         has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

         # 一覧画面で使う
         has_many :following_users, through: :followers, source: :followed
         has_many :follower_users, through: :followeds, source: :follower
         has_one_attached :profile_image


          validates :introduction,
    length: {  maximum: 50 }
            validates :name,
    length: { minimum: 2, maximum: 20 }
    validates :name, uniqueness: true

     def get_profile_image(width, height)
       unless profile_image.attached?
         file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
         profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
       end
       profile_image.variant(resize_to_limit: [width, height]).processed
     end

     #　フォローしたときの処理
     def follow(user_id)
        followers.create(followed_id: user_id)
     end

#　フォローを外すときの処理
     def unfollow(user_id)
        followers.find_by(followed_id: user_id).destroy
     end

#フォローしていればtrueを返す
     def following?(user)
        following_users.include?(user)
     end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @new_book = Book.new
  end

   # 投稿データの保存
  def create
    @user= current_user

    @new_book = Book.new(book_params)
    @books = Book.all
    @book = Book.new(book_params)

    @book.user_id = current_user.id
    if @book.save
        redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render :index
    end
  end

   def index
    @book = Book.new
    @books = Book.all
    @user= current_user
   end



  def show
      @new_book = Book.new
    @book =  Book.find(params[:id])
     @user = @book.user
     @book_comment = BookComment.new

  end

  def edit

    @book = Book.find(params[:id])

    unless @book.user.id == current_user.id
      redirect_to books_path
    end
    @user= current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:alert] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
       render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

    # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  # showアクションにおいて、関連のないユーザーをブロックする
  before_action :block_non_related_users, only: [:show]

  # チャットルームの表示
  def show
    # チャット相手のユーザーを取得
    @user = User.find(params[:id])

    # 現在のユーザーが参加しているチャットルームの一覧を取得
    rooms = current_user.user_rooms.pluck(:room_id)

    # 相手ユーザーとの共有チャットルームが存在するか確認
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      # 共有チャットルームが存在する場合、そのチャットルームを表示
      @room = user_rooms.room
    else
      # 共有チャットルームが存在しない場合、新しいチャットルームを作成
      @room = Room.new
      @room.save

      # チャットルームに現在のユーザーと相手ユーザーを追加
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end

    # チャットルームに関連付けられたメッセージを取得
    @chats = @room.chats

    # 新しいメッセージを作成するための空のChatオブジェクトを生成
    @chat = Chat.new(room_id: @room.id)
  end

  # チャットメッセージの送信
  def create
    # フォームから送信されたメッセージを取得し、現在のユーザーに関連付けて保存
    @chat = current_user.chats.new(chat_params)

    # バリデーションに合格しない場合はエラーを表示
    render :validate unless @chat.save
  end

  # チャットメッセージの削除
  def destroy
    # ログイン中のユーザーに関連するチャットメッセージを削除
    @chat = current_user.chats.find(params[:id])
    @chat.destroy
  end

  private

  # フォームから送信されたパラメータを安全に取得
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  # 関連のないユーザーをブロックする
  def block_non_related_users
    # チャット相手のユーザーを取得
    user = User.find(params[:id])

    # ユーザーがお互いにフォローしているか確認し、していない場合はリダイレクト
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to books_path # リダイレクト先は適切なものに変更しましょう
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
     @book = Book.new(book_params)
  end
  def show
     @book = Book.new
     @user = User.find(params[:id])
    @books = @user.books
    @following_users = @user.following_users
    @follower_users = @user.follower_users
  end


  def index
    @book = Book.new
    @users = User.all
    @user= current_user
  end

  def edit
      is_matching_login_user
    @user = User.find(params[:id])

  end

   def update
       is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:alert] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
       flash.now[:alert] = "error"
       render :edit
    end
   end

   # フォロー一覧
    def follows
      user = User.find(params[:id])
      @users = user.following_users
    end

    # フォロワー一覧
    def followers
      user = User.find(params[:id])
      @user = user.follower_users
    end



  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/4146112a8b.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

             <% if user_signed_in? %>
             <li> <%= link_to user_path(current_user.id), class: 'nav-link text-light'  do %>
           <i class="fas fa-home"></i>
            <%= 'Home' %>
          <% end %></li>
            <li> <%= link_to users_path, class: 'nav-link text-light' do %>
          <i class="fas fa-users"></i>
            <%= 'Users' %>
          <% end %></li>
            <li> <%= link_to books_path, class: 'nav-link text-light' do %>
          <i class="fas fa-book-open"></i>
            <%= 'Books' %>
          <% end %></li>
            <li> <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light'  do %>
         <i class="fas fa-sign-out-alt"></i>
            <%= "Log out" %>
          <% end %></li>




          <% else %>

          <li> <%= link_to root_path, class: "nav-link text-light" do %>
           <i class="fas fa-home"></i> Home
          <% end %></li>
          <li> <%= link_to about_path, class: "nav-link text-light" do %>
          <i class="fas fa-link"></i> About
          <% end %></li>
          <li>  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
          <i class=" fas fa-user-plus"></i> Sign up
            <% end %></li>
          <li> <%= link_to new_user_session_path, class: "nav-link text-light" do %>
         <i class=" fas fa-sign-in-alt"></i> Log in
          <% end %></li>

           <% end %>





            </ul>
          </div>
        </div>
      </nav>
    </header>







  <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <footer>
      <div class="cotainer mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>

      </footer>
  </body>
</html>